### PR TITLE
Fix DBAL 3 compatibility

### LINKED ISSUE #365: Loading fixtures fails with DBAL 3
Using DBAL 3, the command `doctrine:fixtures:load` fails with this error:

```
In ORMPurger.php line 133:

  [Symfony\Component\ErrorHandler\Error\UndefinedMethodError]
  Attempted to call an undefined method named "getFilterSchemaAssetsExpression" of class "Doctrine\DBAL\Configuration".
```

https://github.com/doctrine/data-fixtures/blob/51d3d4880d28951fff42a635a2389f8c63baddc5/lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php#L133

`Configuration::getFilterSchemaAssetsExpression()` has been [removed](https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md#bc-break-removed-previously-deprecated-features) in DBAL 3.

### PR DESCRIPTION
**Pull request by williarin**
Fixes #365 

`doctrine:fixtures:load` command no longer failing with DBAL 3.

### CODE REVIEW

File: lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php [hunk 1]
```diff
@@ -130,7 +130,7 @@ public function purge()
         }
 
         $connection            = $this->em->getConnection();
-        $filterExpr            = $connection->getConfiguration()->getFilterSchemaAssetsExpression();
+        $filterExpr            = method_exists($connection->getConfiguration(), 'getFilterSchemaAssetsExpression') ? $connection->getConfiguration()->getFilterSchemaAssetsExpression() : '';
```
Comment (stof) [inline lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php]: the fallback should be `null` rather than the empty string, to be consistent with what DBAL 2 returns when not using the filter.

Comment (williarin) [reply lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php]: Oops, indeed.

File: lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php [hunk 2]
```diff
@@ -130,7 +130,7 @@ public function purge()
         }
 
         $connection            = $this->em->getConnection();
-        $filterExpr            = $connection->getConfiguration()->getFilterSchemaAssetsExpression();
+        $filterExpr            = method_exists($connection->getConfiguration(), 'getFilterSchemaAssetsExpression') ? $connection->getConfiguration()->getFilterSchemaAssetsExpression() : null;
```
Comment (greg0ire) [inline lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php]: Please use linebreaks :pray:

Comment (williarin) [reply lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php]: I think line breaks will not be coherent with the coding style of this file and I'm not sure it improves readability.
It would look like this:
```php
$connection            = $this->em->getConnection();
$filterExpr            = method_exists($connection->getConfiguration(), 'getFilterSchemaAssetsExpression')
    ? $connection->getConfiguration()->getFilterSchemaAssetsExpression()
    : null;
$emptyFilterExpression = empty($filterExpr);

$schemaAssetsFilter = method_exists($connection->getConfiguration(), 'getSchemaAssetsFilter') ? $connection->getConfiguration()->getSchemaAssetsFilter() : null;
```

Maybe formatting can be delegated to a separate PR?

Comment (greg0ire) [reply lib/Doctrine/Common/DataFixtures/Purger/ORMPurger.php]: The coding style is really defined at the organization level, not at the file level

Breaking inside `method_exists` would result in a better distribution (in your example, the first line still requires horizontal scrolling).

```php
$connection            = $this->em->getConnection();
$filterExpr            = method_exists(
    $connection->getConfiguration(),
    'getFilterSchemaAssetsExpression'
) ? $connection->getConfiguration()->getFilterSchemaAssetsExpression() : null;
$emptyFilterExpression = empty($filterExpr);

$schemaAssetsFilter = method_exists(
    $connection->getConfiguration(),
    'getSchemaAssetsFilter'
) ? $connection->getConfiguration()->getSchemaAssetsFilter() : null;
```

> Maybe formatting can be delegated to a separate PR?

Sure! See https://github.com/doctrine/data-fixtures/pull/367

**Comment by greg0ire** [comment]
To make this complete, I think we should allow dbal 3 the version constraint here: https://github.com/doctrine/data-fixtures/blob/d5ebdb48cdfb2ac2fad612f339f568c098b87caf/composer.json#L27

Currently, we are only testing with `doctrine/dbal` v2 because of it.

**Review by greg0ire — DISMISSED** [review]

**Comment by greg0ire** [comment]
Maybe I approved too fast… what does this PR do?
I think it means that when upgrading to DBAL 3, tables that were previously not purged will suddenly be purged, correct?

EDIT: and then I click "Close and comment" when I mean to click comment :sweat_smile:

**Comment by stof** [comment]
> Maybe I approved too fast… what does this PR do?
> I think it means that when upgrading to DBAL 3, tables that were previously not purged will suddenly be purged, correct?

Well, doctrine/data-fixtures does not *configure* the filtering. It *uses* the filtering configured in DBAL.
If you use the filtering feature of your project, you will already need to migrate to the non-deprecated feature before migrating to DBAL 3.

**Comment by greg0ire** [comment]
Oh right, I didn't notice that the new way was already handled in the lines below (because I didn't know what it looked like). It should be fine then I think.

**Review by greg0ire — APPROVED** [review]

**Review by SenseException — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @williarin !
