### PR TITLE
Rely on object manager proxy resolution

### LINKED ISSUE #417: Cant use an entity with ReferenceRepository if its name ends with Proxy
Since v1.6.0 our tests fail when loading fixtures for entities with a Proxy suffix in their name.

For example with the entity `Path\To\Entities\EntityProxy` we get a `Doctrine\Persistence\Mapping\MappingException: Class 'Path\To\Entities\Entity' does not exist` error.

I think the bug was introduced in https://github.com/doctrine/data-fixtures/pull/409. The `getRealClass` removes the `Proxy` suffix. Maybe the check to remove the suffix `Proxy` could be made more specific to actual proxies?

### PR DESCRIPTION
**Pull request by VincentLanglet**
Suggested by https://github.com/doctrine/persistence/pull/326#issuecomment-1374466942 cc @greg0ire 

Closes https://github.com/doctrine/data-fixtures/pull/419
Closes https://github.com/doctrine/data-fixtures/issues/417

This would be great to try it in a real project.

### CODE REVIEW

**Comment by greg0ire** [comment]
You can use the `Closes` keyword for PRs that should be closed if we merge this as well I think. Needs `vendor/bin/phpcbf`

**Comment by greg0ire** [comment]
Please improve your commit message according to [the contributing guide](https://www.doctrine-project.org/contribute/index.html#working-on-topic-branches).

This is hard to understand, so a good commit message is in order. Here, what happens is that several proxy systems can be in use (the one from `doctrine/common`, and maybe the one Nicolas Grekas recently introduced). By using delegating to the object manager layer, we don't need to know.

**Comment by greg0ire** [comment]
> This would be great to try it in a real project.

@mdevlamynck, can you maybe help with this?

**Review by greg0ire — APPROVED** [review]

File: lib/Doctrine/Common/DataFixtures/ReferenceRepository.php [hunk 1]
```diff
@@ -385,11 +384,7 @@ public function getManager()
      */
     protected function getRealClass($className)
     {
-        if (substr($className, -5) === 'Proxy') {
-            return substr($className, 0, -5);
-        }
-
-        return $className;
+        return $this->manager->getMetadataFactory()->getMetadataFor($className)->getName();
```
Comment (franmomu) [inline lib/Doctrine/Common/DataFixtures/ReferenceRepository.php]:
```suggestion
        return $this->manager->getClassMetadata($className)->getName();
```
This would allow to simplify tests I think

**Comment by mdevlamynck** [comment]
@greg0ire Works in our project.

File: lib/Doctrine/Common/DataFixtures/ReferenceRepository.php [hunk 2]
```diff
@@ -82,7 +81,7 @@ protected function getIdentifier($reference, $uow)
     {
         // In case Reference is not yet managed in UnitOfWork
         if (! $this->hasIdentifier($reference)) {
-            $class = $this->manager->getClassMetadata($this->getRealClass(get_class($reference)));
+            $class = $this->manager->getClassMetadata(get_class($reference));
```
Comment (VincentLanglet) [inline lib/Doctrine/Common/DataFixtures/ReferenceRepository.php:84]: No need to use `getRealClass` here since the getClassMetada is already doing the job.

File: lib/Doctrine/Common/DataFixtures/ReferenceRepository.php (hunk 1 above)
Comment (VincentLanglet) [reply lib/Doctrine/Common/DataFixtures/ReferenceRepository.php]: Thanks, done.

**Comment by greg0ire** [comment]
Might help:

```
cat .git/hooks/pre-push
#!/bin/bash
set -e
echo ''|vendor/bin/phpcs
vendor/bin/phpstan
vendor/bin/psalm
vendor/bin/phpunit
```

**Comment by VincentLanglet** [comment]
Cs is fixed now

**Review by greg0ire — APPROVED** [review]

File: tests/Doctrine/Tests/Common/DataFixtures/ReferenceRepositoryTest.php [hunk 3]
```diff
@@ -129,15 +128,21 @@ public function testUndefinedReference(): void
...
     public function testThrowsExceptionAddingDuplicatedReference(): void
     {
-        $referenceRepository = new ReferenceRepository($this->getMockSqliteEntityManager());
-        $referenceRepository->addReference('duplicated_reference', new stdClass());
+        $em                  = $this->getMockSqliteEntityManager();
+        $referenceRepository = new ReferenceRepository($em);
+
+        $schemaTool = new SchemaTool($em);
+        $schemaTool->dropSchema([]);
+        $schemaTool->createSchema([$em->getClassMetadata(Role::class)]);
```
Comment (franmomu) [inline tests/Doctrine/Tests/Common/DataFixtures/ReferenceRepositoryTest.php]: Are these lines necessary? (since apparently there are no calls to `persist` or `flush`)

Comment (VincentLanglet) [reply tests/Doctrine/Tests/Common/DataFixtures/ReferenceRepositoryTest.php]: Useless indeed so I removed them.

Comment (greg0ire) [reply tests/Doctrine/Tests/Common/DataFixtures/ReferenceRepositoryTest.php]: No need to make a new commit, please amend the first one.

**Review by greg0ire — APPROVED** [review]

**Review by franmomu — APPROVED** [review]

**Comment by greg0ire** [comment]
Thanks @VincentLanglet !
