### PR TITLE
Document possibly null property

### LINKED ISSUE #424: Psalm error for referenceRepository
i followed the example given [here](https://symfony.com/bundles/DoctrineFixturesBundle/current/index.html#accessing-services-from-the-fixtures) to inject a service into the fixture.

now when i'm running psalm it prints out a warning that `referenceRepository` is not set in the constructor

```
ERROR: PropertyNotSetInConstructor - src/DataFixtures/UserFixtures.php:12:7 - Property App\DataFixtures\UserFixtures::$referenceRepository is not defined in constructor of App\DataFixtures\UserFixtures or in any methods called in the constructor (see https://psalm.dev/074)
class UserFixtures extends Fixture
```

my assumption is that it is because in `AbstractFixture` the type hint for `referenceRepository` only mentions `ReferenceRepository` but not null which could theoretically happen

### PR DESCRIPTION
**Pull request by greg0ire**
Fixes #424

### CODE REVIEW

File: src/AbstractFixture.php [hunk 1]
```diff
@@ -29,6 +31,13 @@ public function setReferenceRepository(ReferenceRepository $referenceRepository)
         $this->referenceRepository = $referenceRepository;
     }
 
+    private function referenceRepository(): ReferenceRepository
```
Comment (derrabus) [inline src/AbstractFixture.php]:
```suggestion
    private function getReferenceRepository(): ReferenceRepository
```

File: src/AbstractFixture.php [hunk 2]
```diff
@@ -17,9 +19,9 @@ abstract class AbstractFixture implements SharedFixtureInterface
     /**
      * Fixture reference repository
      *
-     * @var ReferenceRepository
+     * @var ReferenceRepository|null
      */
-    protected $referenceRepository;
+    protected $referenceRepository = null;
```
Comment (derrabus) [inline src/AbstractFixture.php]: Untyped properties are `null` by default and don't need a `null` initialization. The docblock change should be enough.

**Review by derrabus — CHANGES_REQUESTED** [review]

**Review by derrabus — APPROVED** [review]
